name: test suite
on: push
jobs:
  test:
    runs-on: ubuntu@latest
    steps:
      - name: get code from repository
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version:18
      - name: install dependencies
        runs: npm ci
      - name: Run tests
        runs: npm test
      

